# @package _group_
arch:
  _target_: timm.models.create_model
  model_name: mixer_s16_224
  pretrained: False
  drop_rate: 0.0
  drop_path_rate: 0.0


optim:
  _target_: timm.optim.create_optimizer_v2
  optimizer_name: adamw
  learning_rate: 5.0e-4
  weight_decay: 0.05


scheduler:
  _target_: timm.scheduler.create_scheduler
  args:
    epochs: ${epochs}
    sched: cosine
    lr_cycle_mul: 1.0
    min_lr: 5.0e-6
    decay_rate: 0.1
    warmup_lr: 5.0e-7
    warmup_epochs: 20
    warmup_steps: 10000
    lr_cycle_limit: 1
    seed: ${seed}
    cooldown_epochs: 10
    step_per_epoch: True


scaler:
  clip_grad: 5.0
  clip_mode: norm