# @package _group_
arch:
  _target_: timm.models.create_model
  model_name: vit_tiny_patch16_224
  pretrained: False
  drop_rate: 0.0
  drop_path_rate: 0.1


optim:
  _target_: timm.optim.create_optimizer_v2
  optimizer_name: adamw
  learning_rate: 5.0e-4
  weight_decay: 0.05


scheduler:
  _target_: timm.scheduler.create_scheduler
  args:
    epochs: ${epochs}
    sched: cosine
    lr_cycle_mul: 1.0
    min_lr: 1.0e-5
    decay_rate: 0.1
    warmup_lr: 1.0e-6
    warmup_epochs: 5
    # warmup_steps: 10000
    warmup_steps: 5000
    lr_cycle_limit: 1
    seed: ${seed}
    cooldown_epochs: 0
    step_per_epoch: True
    # step_per_epoch: False


scaler:
  clip_grad: null
  clip_mode: norm
